name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install Poetry via pip
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry for in-project venv
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies using Poetry
        run: poetry install

      - name: Activate venv, run pre-commit hooks, and tests with coverage
        run: |
          source .venv/bin/activate
          # Run pre-commit hooks (e.g., Black, Flake8) on all files
          pre-commit run --all-files
          # Run pytest with coverage
          pytest --cov=. --cov-report=xml
          # Generate batch
          coverage-badge -o coverage.svg
